project:
  type: website

website:
  title: "Jessica Chang's Blog"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href:  https://github.com/Jessica19940828
format:
  html:
    theme:
      light: sandstone
      dark: cyborg
    css: styles.css



